/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef } from 'react';
import { 
  X, 
  Upload, 
  Loader2, 
  Plus, 
  Trash2, 
  Image as ImageIcon, 
  Check, 
  Sparkles, 
  ChevronRight,
  Info
} from 'lucide-react';
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { storage } from '../firebase';
import { addProduct, updateProduct, addInventoryLog } from '../services/dbService';
import { Product } from '../types';
import toast from 'react-hot-toast';

interface AdminProductFormProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  productToEdit: Product | null;
  isDarkMode: boolean;
}

export const AdminProductForm: React.FC<AdminProductFormProps> = ({
  isOpen,
  onClose,
  onSuccess,
  productToEdit,
  isDarkMode
}) => {
  const isEditMode = !!productToEdit;
  
  // Core Form State
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('Dresses');
  const [price, setPrice] = useState(150);
  const [originalPrice, setOriginalPrice] = useState<number | undefined>(undefined);
  const [stock, setStock] = useState(15);
  const [sku, setSku] = useState('');
  const [fabric, setFabric] = useState('');
  const [status, setStatus] = useState<'Active' | 'Draft'>('Active');
  
  // Array Lists
  const [images, setImages] = useState<string[]>([]);
  const [sizes, setSizes] = useState<string[]>(['S', 'M', 'L']);
  const [colors, setColors] = useState<{ name: string; hex: string }[]>([]);
  
  // Dynamic flags
  const [isFeatured, setIsFeatured] = useState(false);
  const [isNewArrival, setIsNewArrival] = useState(false);
  
  // UX States
  const [uploading, setUploading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [dragActive, setDragActive] = useState(false);
  
  // Manual additions
  const [imageUrlInput, setImageUrlInput] = useState('');
  const [colorNameInput, setColorNameInput] = useState('');
  const [colorHexInput, setColorHexInput] = useState('#000000');
  
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Available Sizes options
  const availableSizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'Standard'];

  // Color Presets for ultra-fast creation
  const colorPresets = [
    { name: 'Alabaster White', hex: '#F2EFE9' },
    { name: 'Midnight Black', hex: '#1A1A1A' },
    { name: 'Sage Green', hex: '#87A987' },
    { name: 'Blush Pink', hex: '#EFC1C4' },
    { name: 'Navy Blue', hex: '#112233' },
    { name: 'Crimson Red', hex: '#990000' },
    { name: 'Oatmeal Beige', hex: '#E5D3C3' }
  ];

  // Available Categories
  const categories = [
    'Dresses',
    'Tops',
    'Outerwear',
    'Activewear',
    'Accessories',
    'Wedding',
    'Formal',
    'Unstitched'
  ];

  // Set initial form state when productToEdit changes
  useEffect(() => {
    if (productToEdit) {
      setName(productToEdit.name || '');
      setDescription(productToEdit.description || '');
      setCategory(productToEdit.category || 'Dresses');
      setPrice(productToEdit.price || 0);
      setOriginalPrice(productToEdit.originalPrice);
      setStock(productToEdit.stock || 0);
      setSku(productToEdit.sku || '');
      setFabric(productToEdit.fabric || '');
      setStatus(productToEdit.status || 'Active');
      setImages(productToEdit.images || []);
      setSizes(productToEdit.sizes || []);
      setColors(productToEdit.colors || []);
      setIsFeatured(!!productToEdit.isFeatured);
      setIsNewArrival(!!productToEdit.isNewArrival);
    } else {
      // Clear form for add mode
      setName('');
      setDescription('');
      setCategory('Dresses');
      setPrice(150);
      setOriginalPrice(undefined);
      setStock(15);
      setSku('');
      setFabric('');
      setStatus('Active');
      setImages(['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80']);
      setSizes(['S', 'M', 'L']);
      setColors([
        { name: "Alabaster", hex: "#F2EFE9" },
        { name: "Midnight Black", hex: "#1A1A1A" }
      ]);
      setIsFeatured(true);
      setIsNewArrival(true);
    }
  }, [productToEdit, isOpen]);

  // Handle Autogenerate SKU
  const handleGenerateSku = () => {
    const prefix = category.slice(0, 3).toUpperCase();
    const randomSuffix = Math.floor(100 + Math.random() * 900);
    const dateCode = Date.now().toString().slice(-4);
    setSku(`MK-${prefix}-${randomSuffix}${dateCode}`);
    toast.success("SKU Autogenerated!");
  };

  // Toggle Sizes checkmark
  const handleToggleSize = (size: string) => {
    setSizes(prev => 
      prev.includes(size) ? prev.filter(s => s !== size) : [...prev, size]
    );
  };

  // Manual Color Adder
  const handleAddColor = () => {
    if (!colorNameInput.trim()) {
      toast.error('Please specify a color name.');
      return;
    }
    const colorExists = colors.some(c => c.name.toLowerCase() === colorNameInput.trim().toLowerCase());
    if (colorExists) {
      toast.error('Color with this name already exists.');
      return;
    }
    setColors(prev => [...prev, { name: colorNameInput.trim(), hex: colorHexInput }]);
    setColorNameInput('');
    toast.success(`Color "${colorNameInput}" appended.`);
  };

  // Preset Color Click
  const handleApplyPresetColor = (preset: { name: string; hex: string }) => {
    const exists = colors.some(c => c.hex === preset.hex);
    if (exists) {
      setColors(prev => prev.filter(c => c.hex !== preset.hex));
      toast.success(`Removed preset: ${preset.name}`);
    } else {
      setColors(prev => [...prev, preset]);
      toast.success(`Applied preset: ${preset.name}`);
    }
  };

  // Delete specific color
  const handleRemoveColor = (index: number) => {
    setColors(prev => prev.filter((_, idx) => idx !== index));
  };

  // Add pasted Image URL
  const handleAddImageUrl = () => {
    if (!imageUrlInput.trim()) return;
    if (!imageUrlInput.startsWith('http')) {
      toast.error('Please enter a valid HTTP/HTTPS image URL.');
      return;
    }
    setImages(prev => [...prev, imageUrlInput.trim()]);
    setImageUrlInput('');
    toast.success('Web image URL added successfully!');
  };

  // File Upload Logic (Firebase Storage with local base64 fallback)
  const handleFileChange = async (files: FileList | null) => {
    if (!files || files.length === 0) return;
    setUploading(true);
    
    let uploadedCount = 0;
    let fallbackCount = 0;

    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      const storagePath = `products/${Date.now()}-${file.name}`;
      const imageRef = ref(storage, storagePath);

      try {
        // Attempt upload to Firebase Storage
        const uploadResult = await uploadBytes(imageRef, file);
        const downloadUrl = await getDownloadURL(uploadResult.ref);
        
        setImages(prev => [...prev, downloadUrl]);
        uploadedCount++;
      } catch (storageError) {
        console.warn("Firebase Storage blocked or unconfigured, falling back to base64 encoding:", storageError);
        // Fallback: Convert to Base64
        try {
          const base64String = await new Promise<string>((resolve, reject) => {
            const reader = new FileReader();
            reader.readAsDataURL(file);
            reader.onload = () => resolve(reader.result as string);
            reader.onerror = (e) => reject(e);
          });

          setImages(prev => [...prev, base64String]);
          fallbackCount++;
        } catch (base64Err) {
          toast.error(`Failed to process file "${file.name}"`);
        }
      }
    }

    setUploading(false);

    if (uploadedCount > 0 && fallbackCount > 0) {
      toast.success(`Uploaded ${uploadedCount} to storage, processed ${fallbackCount} locally!`);
    } else if (uploadedCount > 0) {
      toast.success(`Successfully uploaded ${uploadedCount} image(s) to Firebase Storage!`);
    } else if (fallbackCount > 0) {
      toast.success(`Processed ${fallbackCount} image(s) locally as offline base64 strings!`);
    }
  };

  // Drag Events UX
  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setDragActive(true);
    } else if (e.type === 'dragleave') {
      setDragActive(false);
    }
  };

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      await handleFileChange(e.dataTransfer.files);
    }
  };

  // Reorder / Change Primary Image
  const handleSetPrimaryImage = (index: number) => {
    if (index === 0) return;
    setImages(prev => {
      const copy = [...prev];
      const target = copy[index];
      copy.splice(index, 1);
      return [target, ...copy];
    });
    toast.success("Set as primary display image.");
  };

  // Delete image from form state
  const handleRemoveImage = (index: number) => {
    setImages(prev => prev.filter((_, idx) => idx !== index));
    toast.success("Image removed.");
  };

  // Discount percentage helper
  const discountPercentage = originalPrice && originalPrice > price
    ? Math.round(((originalPrice - price) / originalPrice) * 100)
    : 0;

  // Form Submit Handler (CRUD logic)
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!name.trim()) {
      toast.error('Please provide a product name.');
      return;
    }
    if (!description.trim()) {
      toast.error('Please write a short description.');
      return;
    }
    if (images.length === 0) {
      toast.error('Please upload or provide at least one product image.');
      return;
    }
    if (sizes.length === 0) {
      toast.error('Please check at least one size.');
      return;
    }

    setSubmitting(true);

    try {
      const finalSku = sku.trim() || `MK-${category.slice(0,3).toUpperCase()}-${Math.floor(1000 + Math.random()*9000)}`;
      
      const payload: Product = {
        id: isEditMode ? productToEdit.id : `prod-${Date.now()}`,
        name: name.trim(),
        description: description.trim(),
        price: Number(price),
        originalPrice: originalPrice ? Number(originalPrice) : undefined,
        category,
        images,
        sizes,
        colors,
        stock: Number(stock),
        sku: finalSku,
        fabric: fabric.trim() || 'Premium Sustainable Weave',
        status,
        isFeatured,
        isNewArrival,
        rating: isEditMode ? (productToEdit.rating || 5.0) : 5.0,
        reviewCount: isEditMode ? (productToEdit.reviewCount || 0) : 0,
        createdAt: isEditMode ? (productToEdit.createdAt || Date.now()) : Date.now(),
        brand: isEditMode ? (productToEdit.brand || 'Atelier MK') : 'Atelier MK'
      };

      if (isEditMode) {
        await updateProduct(productToEdit.id, payload);
        
        // Log stock level difference if changed
        if (productToEdit.stock !== payload.stock) {
          await addInventoryLog({
            productId: productToEdit.id,
            productName: payload.name,
            changeType: 'manual_adjustment',
            quantityChanged: payload.stock - productToEdit.stock,
            oldStock: productToEdit.stock,
            newStock: payload.stock,
            notes: `Updated stock via form (from ${productToEdit.stock} to ${payload.stock})`
          });
        }

        toast.success(`"${name}" updated successfully in Firestore!`, { icon: '📝' });
      } else {
        await addProduct(payload);

        // Log initial product stock
        await addInventoryLog({
          productId: payload.id,
          productName: payload.name,
          changeType: 'add_product',
          quantityChanged: payload.stock,
          oldStock: 0,
          newStock: payload.stock,
          notes: `Published "${payload.name}" with initial stock`
        });

        toast.success(`"${name}" published successfully to Firestore!`, { icon: '📦' });
      }

      onSuccess();
      onClose();
    } catch (err) {
      console.error(err);
      toast.error(isEditMode ? 'Failed to update product details.' : 'Failed to publish new product.');
    } finally {
      setSubmitting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <>
      {/* Backdrop */}
      <div 
        className="fixed inset-0 bg-black/70 z-50 backdrop-blur-xs transition-opacity duration-300" 
        onClick={onClose}
      />

      {/* Drawer */}
      <div className={`fixed inset-y-0 right-0 w-full sm:max-w-2xl shadow-2xl z-50 flex flex-col justify-between animate-in slide-in-from-right duration-300 ${
        isDarkMode ? 'bg-zinc-900 text-zinc-100' : 'bg-white text-zinc-900'
      }`}>
        
        {/* Header */}
        <div className={`px-6 py-5 border-b flex items-center justify-between ${
          isDarkMode ? 'border-zinc-800' : 'border-neutral-200'
        }`}>
          <div>
            <h3 className="text-sm font-black uppercase tracking-wider font-mono">
              {isEditMode ? 'EDIT REGISTRY PRODUCT' : 'APPEND NEW APPAREL PRODUCT'}
            </h3>
            <p className="text-[10px] text-zinc-400 font-mono mt-0.5">
              {isEditMode ? `ID: ${productToEdit.id}` : 'CREATING NEW luxury design'}
            </p>
          </div>
          <button 
            onClick={onClose} 
            className={`p-2 rounded-full cursor-pointer transition-colors ${
              isDarkMode ? 'hover:bg-zinc-800 text-zinc-400 hover:text-white' : 'hover:bg-neutral-150 text-zinc-500 hover:text-black'
            }`}
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Scrollable Form Body */}
        <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto px-6 py-6 space-y-6 text-xs">
          
          {/* Grid: Name & Category */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block">Product Name</label>
              <input
                type="text"
                required
                placeholder="Silk Evening Gown"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className={`w-full rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-black border transition-all ${
                  isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white focus:border-zinc-700' : 'bg-white border-neutral-300 text-zinc-900 focus:border-neutral-800'
                }`}
              />
            </div>

            <div className="space-y-1.5">
              <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block">Collection Category</label>
              <select
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                className={`w-full rounded-xl px-4 py-3 outline-none border text-sm cursor-pointer transition-all ${
                  isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white focus:border-zinc-700' : 'bg-white border-neutral-300 text-zinc-900 focus:border-neutral-800'
                }`}
              >
                {categories.map(cat => (
                  <option key={cat} value={cat}>{cat}</option>
                ))}
              </select>
            </div>
          </div>

          {/* Description */}
          <div className="space-y-1.5">
            <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block">Editorial Description</label>
            <textarea
              required
              rows={3}
              placeholder="Exquisite, flowing silk cut meticulously with a tailored waistline..."
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className={`w-full rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-black border transition-all ${
                isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white focus:border-zinc-700' : 'bg-white border-neutral-300 text-zinc-900 focus:border-neutral-800'
              }`}
            />
          </div>

          {/* Financials & Stock: Price, Original Price, Stock, Status */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="space-y-1.5">
              <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block">Price ($)</label>
              <input
                type="number"
                required
                min="0"
                value={price}
                onChange={(e) => setPrice(Number(e.target.value))}
                className={`w-full rounded-xl px-4 py-2.5 text-sm font-mono focus:outline-none border transition-all ${
                  isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white' : 'bg-white border-neutral-300 text-zinc-900'
                }`}
              />
            </div>

            <div className="space-y-1.5">
              <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block flex items-center justify-between">
                <span>Original Price</span>
                <span className="text-[10px] text-zinc-500 lowercase font-normal">(Optional)</span>
              </label>
              <input
                type="number"
                min="0"
                placeholder="No discount"
                value={originalPrice || ''}
                onChange={(e) => setOriginalPrice(e.target.value ? Number(e.target.value) : undefined)}
                className={`w-full rounded-xl px-4 py-2.5 text-sm font-mono focus:outline-none border transition-all ${
                  isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white' : 'bg-white border-neutral-300 text-zinc-900'
                }`}
              />
            </div>

            <div className="space-y-1.5">
              <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block">Stock Level</label>
              <input
                type="number"
                required
                min="0"
                value={stock}
                onChange={(e) => setStock(Number(e.target.value))}
                className={`w-full rounded-xl px-4 py-2.5 text-sm font-mono focus:outline-none border transition-all ${
                  isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white' : 'bg-white border-neutral-300 text-zinc-900'
                }`}
              />
            </div>

            <div className="space-y-1.5">
              <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block">Status</label>
              <select
                value={status}
                onChange={(e) => setStatus(e.target.value as 'Active' | 'Draft')}
                className={`w-full rounded-xl px-4 py-2.5 outline-none border text-sm cursor-pointer transition-all ${
                  isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white' : 'bg-white border-neutral-300 text-zinc-900'
                }`}
              >
                <option value="Active">Active</option>
                <option value="Draft">Draft</option>
              </select>
            </div>
          </div>

          {/* Discount Indicator */}
          {discountPercentage > 0 && (
            <div className={`p-3 rounded-2xl flex items-center gap-2 font-mono ${
              isDarkMode ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 'bg-emerald-50 text-emerald-700 border border-emerald-200'
            }`}>
              <Sparkles className="w-4 h-4 animate-pulse shrink-0" />
              <span>Discount Active: <strong>{discountPercentage}% off</strong> original designer price!</span>
            </div>
          )}

          {/* SKU & Fabric */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block flex items-center justify-between">
                <span>SKU Code</span>
                <button 
                  type="button" 
                  onClick={handleGenerateSku}
                  className="text-[10px] text-zinc-400 hover:text-black font-semibold uppercase hover:underline transition-colors font-mono cursor-pointer"
                >
                  Generate Code
                </button>
              </label>
              <input
                type="text"
                placeholder="e.g. MK-DRS-3942"
                value={sku}
                onChange={(e) => setSku(e.target.value)}
                className={`w-full rounded-xl px-4 py-2.5 text-sm font-mono focus:outline-none border transition-all ${
                  isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white' : 'bg-white border-neutral-300 text-zinc-900'
                }`}
              />
            </div>

            <div className="space-y-1.5">
              <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block">Fabric composition</label>
              <input
                type="text"
                placeholder="e.g. 100% Organically Certified Flax Linen"
                value={fabric}
                onChange={(e) => setFabric(e.target.value)}
                className={`w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none border transition-all ${
                  isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white' : 'bg-white border-neutral-300 text-zinc-900'
                }`}
              />
            </div>
          </div>

          {/* Sizes Selection */}
          <div className="space-y-2">
            <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block">Available Sizes</label>
            <div className="flex gap-2.5 flex-wrap">
              {availableSizes.map(size => {
                const isSelected = sizes.includes(size);
                return (
                  <button
                    key={size}
                    type="button"
                    onClick={() => handleToggleSize(size)}
                    className={`px-4 py-2 rounded-xl text-xs font-bold font-mono transition-all border cursor-pointer ${
                      isSelected 
                        ? 'bg-black text-white border-black' 
                        : isDarkMode
                          ? 'border-zinc-800 hover:border-zinc-600 text-zinc-400 hover:text-zinc-200'
                          : 'border-neutral-300 hover:border-neutral-500 text-zinc-600 hover:text-black'
                    }`}
                  >
                    {size}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Colors management */}
          <div className="space-y-3">
            <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block">Color variants</label>
            
            {/* Swatchpresets shortcut */}
            <div className="space-y-1.5">
              <span className="text-[10px] text-zinc-500 font-mono uppercase block">Presets Quick-Apply</span>
              <div className="flex gap-2 flex-wrap">
                {colorPresets.map(preset => {
                  const alreadySelected = colors.some(c => c.hex === preset.hex);
                  return (
                    <button
                      key={preset.name}
                      type="button"
                      onClick={() => handleApplyPresetColor(preset)}
                      className={`inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-xl border text-[10px] font-mono cursor-pointer transition-all ${
                        alreadySelected 
                          ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30' 
                          : isDarkMode 
                            ? 'border-zinc-800 bg-zinc-900 hover:border-zinc-700 text-zinc-400 hover:text-white' 
                            : 'border-neutral-250 bg-neutral-50 hover:border-neutral-400 text-zinc-600 hover:text-black'
                      }`}
                    >
                      <span 
                        className="w-3.5 h-3.5 rounded-full border border-neutral-500/20 shrink-0" 
                        style={{ backgroundColor: preset.hex }} 
                      />
                      <span>{preset.name}</span>
                      {alreadySelected && <Check className="w-3 h-3 text-emerald-400" />}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Custom Color Inputs */}
            <div className="flex gap-2 items-end flex-wrap pt-2">
              <div className="space-y-1 flex-1 min-w-[150px]">
                <span className="text-[10px] text-zinc-500 font-mono uppercase">Color Name</span>
                <input
                  type="text"
                  placeholder="e.g. Lavender Pearl"
                  value={colorNameInput}
                  onChange={(e) => setColorNameInput(e.target.value)}
                  className={`w-full rounded-xl px-3 py-2 text-xs focus:outline-none border transition-all ${
                    isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white' : 'bg-white border-neutral-300 text-zinc-900'
                  }`}
                />
              </div>

              <div className="space-y-1">
                <span className="text-[10px] text-zinc-500 font-mono uppercase block">Hex Swatch</span>
                <div className="flex items-center gap-2">
                  <input
                    type="color"
                    value={colorHexInput}
                    onChange={(e) => setColorHexInput(e.target.value)}
                    className="w-8 h-8 rounded-lg cursor-pointer border border-neutral-500/20"
                  />
                  <input
                    type="text"
                    value={colorHexInput}
                    onChange={(e) => setColorHexInput(e.target.value)}
                    className={`w-20 rounded-xl px-2.5 py-1.5 text-xs font-mono focus:outline-none border ${
                      isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white' : 'bg-white border-neutral-300 text-zinc-900'
                    }`}
                  />
                </div>
              </div>

              <button
                type="button"
                onClick={handleAddColor}
                className="inline-flex items-center justify-center bg-black hover:bg-neutral-800 text-white px-4 py-2 rounded-xl text-xs font-mono font-bold uppercase cursor-pointer border border-zinc-700 shadow"
              >
                Add Swatch
              </button>
            </div>

            {/* Selected Custom Swatches Grid */}
            {colors.length > 0 && (
              <div className="flex gap-2 flex-wrap pt-2">
                {colors.map((color, idx) => (
                  <div 
                    key={idx} 
                    className={`flex items-center gap-1.5 pl-2.5 pr-1.5 py-1 rounded-full border text-[11px] font-medium font-mono ${
                      isDarkMode ? 'bg-zinc-950 border-zinc-800' : 'bg-neutral-50 border-neutral-200'
                    }`}
                  >
                    <span 
                      className="w-3.5 h-3.5 rounded-full border border-neutral-500/10 shrink-0" 
                      style={{ backgroundColor: color.hex }} 
                    />
                    <span>{color.name}</span>
                    <button 
                      type="button" 
                      onClick={() => handleRemoveColor(idx)}
                      className="p-1 hover:bg-red-500/10 text-neutral-400 hover:text-red-500 rounded-full transition-colors cursor-pointer"
                    >
                      <X className="w-3.5 h-3.5" />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Drag and Drop Image Upload + Multiple Images Section */}
          <div className="space-y-4 border-t border-neutral-100/10 pt-4">
            <div className="flex items-center justify-between">
              <label className="font-bold text-zinc-400 uppercase font-mono tracking-wider block">Product Showcase Gallery</label>
              <span className="text-[10px] text-zinc-500 font-mono">({images.length} images uploaded)</span>
            </div>

            {/* Drag & Drop Zone */}
            <div 
              onDragEnter={handleDrag}
              onDragLeave={handleDrag}
              onDragOver={handleDrag}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
              className={`border-2 border-dashed rounded-2xl p-6 text-center cursor-pointer transition-all flex flex-col items-center justify-center space-y-2 ${
                dragActive 
                  ? 'border-emerald-500 bg-emerald-500/10' 
                  : isDarkMode 
                    ? 'border-zinc-800 bg-zinc-950 hover:bg-zinc-850/50 hover:border-zinc-700' 
                    : 'border-neutral-300 bg-neutral-50 hover:bg-neutral-100/50 hover:border-neutral-400'
              }`}
            >
              <input 
                ref={fileInputRef}
                type="file"
                multiple
                accept="image/*"
                onChange={(e) => handleFileChange(e.target.files)}
                className="hidden"
              />
              {uploading ? (
                <>
                  <Loader2 className="w-8 h-8 animate-spin text-zinc-400" />
                  <p className="font-semibold text-zinc-400 font-mono">Uploading photos directly to Firebase Storage...</p>
                </>
              ) : (
                <>
                  <Upload className="w-8 h-8 text-zinc-400 animate-bounce" />
                  <p className="font-semibold font-mono text-zinc-300">Drag & Drop files here, or click to browse</p>
                  <p className="text-[10px] text-zinc-500">Supports PNG, JPG, WEBP formats (multiple files allowed)</p>
                </>
              )}
            </div>

            {/* Paste URL Input for secondary convenience */}
            <div className="flex gap-2 items-center">
              <input
                type="url"
                placeholder="Or paste any Web Image Asset URL..."
                value={imageUrlInput}
                onChange={(e) => setImageUrlInput(e.target.value)}
                className={`flex-1 rounded-xl px-4 py-2 text-xs font-mono focus:outline-none border ${
                  isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white' : 'bg-white border-neutral-300 text-zinc-900'
                }`}
              />
              <button
                type="button"
                onClick={handleAddImageUrl}
                className="bg-black text-white px-4 py-2 rounded-xl text-xs font-mono font-bold uppercase cursor-pointer border border-zinc-700 hover:bg-neutral-800"
              >
                Add Link
              </button>
            </div>

            {/* Gallery Grid showing uploaded images with control */}
            {images.length > 0 ? (
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2">
                {images.map((img, idx) => (
                  <div 
                    key={idx} 
                    className={`relative rounded-xl border overflow-hidden group h-32 flex flex-col justify-between ${
                      idx === 0 
                        ? 'border-black ring-2 ring-black/40' 
                        : isDarkMode ? 'border-zinc-800' : 'border-neutral-200'
                    }`}
                  >
                    <img 
                      src={img} 
                      alt="" 
                      className="absolute inset-0 w-full h-full object-cover z-0" 
                      referrerPolicy="no-referrer" 
                    />
                    
                    {/* Dark gradient overlay for action buttons */}
                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity z-10" />

                    {/* Badge indicator */}
                    <div className="absolute top-1.5 left-1.5 z-20">
                      {idx === 0 ? (
                        <span className="bg-black text-white text-[9px] font-black font-mono px-1.5 py-0.5 rounded uppercase">Primary</span>
                      ) : (
                        <button
                          type="button"
                          onClick={() => handleSetPrimaryImage(idx)}
                          className="bg-zinc-900/90 text-zinc-300 hover:text-white text-[9px] font-black font-mono px-1.5 py-0.5 rounded uppercase z-20 cursor-pointer shadow hover:bg-black transition-all"
                        >
                          Make Primary
                        </button>
                      )}
                    </div>

                    {/* Delete Action button */}
                    <button
                      type="button"
                      onClick={() => handleRemoveImage(idx)}
                      className="absolute bottom-1.5 right-1.5 bg-red-500 hover:bg-red-600 text-white p-1.5 rounded-lg z-20 opacity-0 group-hover:opacity-100 transition-all cursor-pointer shadow"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                ))}
              </div>
            ) : (
              <div className={`p-8 border border-dashed rounded-2xl text-center text-zinc-500 italic ${
                isDarkMode ? 'bg-zinc-950/30 border-zinc-850' : 'bg-neutral-50 border-neutral-250'
              }`}>
                No showcase images in current gallery. Upload or paste a URL above!
              </div>
            )}
          </div>

          {/* Quick Info Box */}
          <div className={`p-3.5 rounded-2xl flex items-start gap-2.5 font-sans ${
            isDarkMode ? 'bg-zinc-950/50 text-zinc-400 border border-zinc-850' : 'bg-neutral-50 text-zinc-600 border border-neutral-200'
          }`}>
            <Info className="w-4 h-4 shrink-0 mt-0.5 text-zinc-500" />
            <p className="text-[10px] leading-relaxed">
              Upon publishing, this design will instantly synchronise with the Firestore catalog database. Users on the retail site will be able to view stock status, read description compositions, and purchase this product in real-time.
            </p>
          </div>

          {/* Flags checks: Featured & New Arrival */}
          <div className="flex gap-6 py-2 border-t border-neutral-100/10 pt-4 flex-wrap">
            <label className="flex items-center gap-2 font-semibold cursor-pointer text-sm">
              <input
                type="checkbox"
                checked={isFeatured}
                onChange={(e) => setIsFeatured(e.target.checked)}
                className="w-4 h-4 rounded text-black border-gray-300 focus:ring-black accent-black cursor-pointer"
              />
              <span className="font-mono text-xs uppercase tracking-wider text-zinc-400">Featured Design</span>
            </label>

            <label className="flex items-center gap-2 font-semibold cursor-pointer text-sm">
              <input
                type="checkbox"
                checked={isNewArrival}
                onChange={(e) => setIsNewArrival(e.target.checked)}
                className="w-4 h-4 rounded text-black border-gray-300 focus:ring-black accent-black cursor-pointer"
              />
              <span className="font-mono text-xs uppercase tracking-wider text-zinc-400">New Arrival Collection</span>
            </label>
          </div>

          {/* Actions: Save button */}
          <button
            type="submit"
            disabled={submitting}
            className="w-full bg-black hover:bg-neutral-850 text-white border border-zinc-700 font-mono text-xs font-bold py-4 rounded-xl tracking-widest uppercase flex items-center justify-center gap-2 shadow-lg transition-all cursor-pointer mt-4"
          >
            {submitting ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>SAVING DESIGN piece TO FIRESTORE...</span>
              </>
            ) : (
              <span>{isEditMode ? 'SAVE AND PUBLISH CHANGES' : 'PUBLISH DESIGN TO CATALOG'}</span>
            )}
          </button>

        </form>
      </div>
    </>
  );
};
